{{ if .Values.pvc.create }}
{{- if not .Values.pvc.existingClaim -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "seafile.pvcname" . }}
  labels: {{ include "seafile.labels" . | indent 4 }}
  annotations:
    "helm.sh/resource-policy": {{ default "keep" .Values.pvc.resourcePolicy }}

spec:
  storageClassName: {{ .Values.pvc.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{ end }}
{{- end -}}
