---
apiVersion: v1
kind: Service

metadata:
  name: {{ template "seafile.resname" . }}
  labels: {{ include "seafile.labels" . | indent 4 }}
    component: seafile

spec:

  selector: {{ include "seafile.labels-selector" . | indent 4 }}
    component: seafile

  ports:
  - port: 80
    targetPort: 80
