{{ if .Values.hedgedoc.security.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hedgedoc.shortName" . }}-session
  labels:
    app.kubernetes.io/component: sessionSecret
    {{ include "hedgedoc.labels" . | nindent 4 }}
stringData:
  CMD_SESSION_SECRET: {{ .Values.hedgedoc.security.sessionSecret | quote }}
{{ end }}
