---
{{ if not .Values.icinga2.master2.disable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "icinga2.resname" . }}-master-2
  labels: {{ include "icinga2.labels" . | indent 4 }}
    component: icinga2-master-2

spec:

  selector: {{ include "icinga2.labels-selector" . | indent 4 }}
    component: icinga2-master-2

  ports:
    - name: icinga2
      port: 5665
      targetPort: 5665
    {{ if .Values.icinga2.IcingaDB -}}
    - name: redis
      port: 6380
      targetPort: 6380
    {{- end }}
    - name: certsvc
      port: 8080
      targetPort: 8080
{{ end }}
