---
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "icinga2.resname" . }}-web
  labels: {{ include "icinga2.labels" . | indent 4 }}
    component: web
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
{{- if .Values.icinga2.ingressClassName }}
  ingressClassName: {{ .Values.icinga2.ingressClassName }}
{{- end }}
  tls:
    {{ if .Values.icinga2.web.tlsSecret -}}
    - secretName: {{ .Values.icinga2.web.tlsSecret }}
    {{- else }}
    - secretName: {{ template "icinga2.resname" . }}-web-tls
    {{- end }}
      hosts:
        - {{ .Values.icinga2.web.hostname }}
  rules:
    - host: {{ .Values.icinga2.web.hostname }}
      http:
        paths:
          - path: "/"
            {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            {{- end }}
            backend:
            {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: {{ template "icinga2.resname" . }}-web
                port:
                  number: 80
            {{- else }}
              serviceName: {{ template "icinga2.resname" . }}-web
              servicePort: 80
            {{- end }}
