apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fluent-bit-agent.resname" . }}
  labels: {{ include "fluent-bit-agent.labels" . | indent 4 }}
    component: agent
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels: {{ include "fluent-bit-agent.labels" . | indent 6 }}
      component: agent

  template:
    metadata:
      labels: {{ include "fluent-bit-agent.labels" . | indent 8 }}
        component: agent
        kubernetes.io/cluster-service: "true"
        revision: {{ .Release.Revision | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:

      - name: agent
        image: {{ .Values.repository }}:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        env:
        - name: K8S_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # - name: OUTPUT_GELF_HOST
        #   value: graylog.ops.dhswt.de
        # - name: OUTPUT_GELF_PORT
        #   value: "32201"

        ports:
          - containerPort: 2020

        volumeMounts:
        - name: var-log
          mountPath: /var/log
        - name: var-lib-docker-containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/

        resources:
          {{ toYaml .Values.resources | indent 10 | trim }}

      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      terminationGracePeriodSeconds: 10
      volumes:
      - name: var-log
        hostPath:
          path: /var/log
      - name: var-lib-docker-containers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: {{ template "fluent-bit-agent.resname" . }}
      serviceAccountName: {{ template "fluent-bit-agent.resname" . }}
      tolerations:
      - operator: Exists
