---
# Source: icinga2-agent/templates/agent-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testname-agent
  namespace: default
---
# Source: icinga2-agent/templates/companion-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testname-companion
  namespace: default
---
# Source: icinga2-agent/templates/agent-config-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: testname-agent
  labels:     
    app: icinga2-agent
    chart: icinga2-agent-0.1.6
    release: testname
    heritage: Helm
    component: agent

# data:

stringData:

  IC2_DIRECTOR_URI:     "https://icinga2.example.com/icinga/director"
  IC2_DIRECTOR_USER:    "director"
  IC2_DIRECTOR_PASS:    "pass"

  IC2_MASTER:           "master1.icinga2.example.com"
  IC2_MASTER_2:         ""
  IC2_MASTER_PORT:      "5665"

  IC2_AGENT_PUSH:                   "0"
  IC2_ETH_INT:                      "eth0"
  IC2_HOST_DISTRIBUTION:            ""
  IC2_HOST_DISTRIBUTION_VERSION:    ""
  IC2_ROOT_DEVICE:                  ""
  IC2_INSTANCE_TYPE:                "cloud"
  
  IC2_HAPROXY_URL:                  "http://172.17.0.1:1936/;csv"
  
  
  IC2_DETECT_INGRESS:               "true"
  
  

  # kubernetes
  
  IC2_KUBE_HOST:               "kubernetes.default"
  IC2_KUBE_PORT:               "443"
  IC2_KUBE_SCHEME:             "https"
  
  

  # agent config variables
  K8S_AUTO_DEREGISTER: "1"
---
# Source: icinga2-agent/templates/companion-config-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: testname-companion
  labels:     
    app: icinga2-agent
    chart: icinga2-agent-0.1.6
    release: testname
    heritage: Helm
    component: companion

# data:

stringData:

  IC2_DIRECTOR_URI:     "https://icinga2.example.com/icinga/director"
  IC2_DIRECTOR_USER:    "director"
  IC2_DIRECTOR_PASS:    "pass"

  IC2_MASTER:           "master1.icinga2.example.com"
  IC2_MASTER_2:         ""
  IC2_MASTER_PORT:      "5665"

  IC2_AGENT_PUSH:                   "1"
  IC2_INSTANCE_TYPE:                "companion"

  # kubernetes
  
  IC2_KUBE_HOST:               "kubernetes.default"
  IC2_KUBE_PORT:               "443"
  IC2_KUBE_SCHEME:             "https"
  
  

  # agent config variables
  K8S_AUTO_DEREGISTER: "1"
---
# Source: icinga2-agent/templates/agent-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: testname-agent
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - services
  verbs: ["get", "list", "watch"]
---
# Source: icinga2-agent/templates/companion-rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: testname-companion
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
---
# Source: icinga2-agent/templates/agent-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: testname-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testname-agent
subjects:
- kind: ServiceAccount
  name: testname-agent
  namespace: default
---
# Source: icinga2-agent/templates/companion-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: testname-companion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testname-companion
subjects:
  - kind: ServiceAccount
    name: testname-companion
    namespace: default
---
# Source: icinga2-agent/templates/companion-service.yaml
apiVersion: v1
kind: Service

metadata:
  name: testname-companion
  labels:     
    app: icinga2-agent
    chart: icinga2-agent-0.1.6
    release: testname
    heritage: Helm
    component: companion

spec:

  selector:     
    app: icinga2-agent
    release: testname
    component: companion

  ports:
  - port: 5665
    targetPort: 5665
---
# Source: icinga2-agent/templates/agent-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testname
  labels:     
    app: icinga2-agent
    chart: icinga2-agent-0.1.6
    release: testname
    heritage: Helm
    component: agent

spec:

  selector:
    matchLabels:       
      app: icinga2-agent
      chart: icinga2-agent-0.1.6
      release: testname
      heritage: Helm
      component: agent

  template:

    metadata:
      labels:         
        app: icinga2-agent
        chart: icinga2-agent-0.1.6
        release: testname
        heritage: Helm
        component: agent
        revision: "1"

    spec:
      enableServiceLinks: false
      terminationGracePeriodSeconds: 10
      serviceAccountName: testname-agent

      # priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/disk-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/pid-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/unschedulable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/network-unavailable
          operator: Exists

      hostNetwork: true
      hostPID: true

      

      containers:
        - name: icinga2-agent
          image: registry.gitlab.com/olemisea/icinga2-agent-docker:minion-0.5
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true

          env:
            - name: IC2_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: IC2_AGENT_ENDPOINT
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - secretRef:
                name: testname-agent

          ports:
            - name: icinga
              containerPort: 5665
            #  hostPort: 5665

          volumeMounts:
            
            
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: efi
              mountPath: /boot/efi
            - name: proc
              mountPath: /host/proc
            - name: sys
              mountPath: /host/sys
            - name: run
              mountPath: /host/run
            - name: system-bus-socket
              mountPath: /run/dbus/system_bus_socket
            - name: fstab
              mountPath: /etc/fstab
              readOnly: true
            - name: os-release
              mountPath: /host/etc/os-release
              readOnly: true
            - name: dpkg-status
              mountPath: /host/var/lib/dpkg/status
              readOnly: true

          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi

          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "[ -f /var/lib/icinga2/certs/ticket ] && [ -f /var/lib/icinga2/certs/trusted-master.crt ]"
            initialDelaySeconds: 120
            periodSeconds: 30
          
          lifecycle:
            preStop:
              exec:
                command: [/bin/bash, -c, /cont-term.sh]

      volumes:
        
        
        - name: efi
          hostPath:
            path: /boot/efi
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: run
          hostPath:
            path: /run
        - name: system-bus-socket
          hostPath:
            path: /run/dbus/system_bus_socket
        - name: fstab
          hostPath:
            path: /etc/fstab
        - name: os-release
          hostPath:
            path: /etc/os-release
        - name: dpkg-status
          hostPath:
            path: /var/lib/dpkg/status
---
# Source: icinga2-agent/templates/companion-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: testname-companion
  labels:     
    app: icinga2-agent
    chart: icinga2-agent-0.1.6
    release: testname
    heritage: Helm
    component: companion

spec:
  replicas: 1
  serviceName: testname-companion

  selector:
    matchLabels:       
      app: icinga2-agent
      chart: icinga2-agent-0.1.6
      release: testname
      heritage: Helm
      component: companion

  template:

    metadata:
      labels:         
        app: icinga2-agent
        chart: icinga2-agent-0.1.6
        release: testname
        heritage: Helm
        component: companion
        revision: "1"

    spec:
      enableServiceLinks: false
      terminationGracePeriodSeconds: 10
      serviceAccountName: testname-companion

      # priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/disk-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/pid-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/unschedulable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/network-unavailable
          operator: Exists

      

      

      containers:
        - name: icinga2-companion
          image: registry.gitlab.com/olemisea/icinga2-agent-docker:minion-0.5
          imagePullPolicy: IfNotPresent

          envFrom:
            - secretRef:
                name: testname-companion

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            

          ports:
            - name: icinga
              containerPort: 5665
            #  hostPort: 5665

          volumeMounts:
            - name: additional-plugins
              mountPath: /additional-plugins
            
            

          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi

          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "[ -f /var/lib/icinga2/certs/ticket ] && [ -f /var/lib/icinga2/certs/trusted-master.crt ]"
            initialDelaySeconds: 120
            periodSeconds: 30
          
          lifecycle:
            preStop:
              exec:
                command: [/bin/bash, -c, /cont-term.sh]

      volumes:
        - name: additional-plugins
          emptyDir: {}
