kind: Secret
apiVersion: v1
metadata:
  name: {{ include "bookstack.fullname" . }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.mysql.mysqlHost | b64enc }}
  DB_DATABASE: {{ .Values.mysql.mysqlDatabase | b64enc }}
  DB_USERNAME: {{ .Values.mysql.mysqlUser | b64enc }}
  DB_PASSWORD: {{ .Values.mysql.mysqlPassword | b64enc }}
