apiVersion: v2
appVersion: 0.69.2
description: The outline helm chart to deploy outline in kubernetes clusters.
home: https://encircle360.com
keywords:
- outline
- wiki
- helm
- chart
- kubernetes
- s3
- minio
- postgresql
- mongodb
- knowledge
maintainers:
- email: hello@encircle360.com
  name: encircle360 GmbH
  url: https://encircle360.com
name: outline
sources:
- https://gitlab.com/encircle360-oss/helm-charts/outline
- https://github.com/encircle360-oss/outline-helm-chart
version: 0.0.8
