apiVersion: v2
description: Generic Seafile Deployment.
name: seafile
version: 13.0.13
appVersion: "13.0-latest"
keywords:
- seafile
home: https://github.com/schmitzis/helm-charts
# icon: https://....
sources:
- https://github.com/schmitzis/helm-charts
maintainers:
- name: Michael Schmitz
  email: git@schmitz-quiddelbach.de
