image: schmitzis/monorepo:seafile-13.0-latest
pullPolicy: IfNotPresent
imagePullSecret: ""

pvc:
  create: true
  size: 20Gi
  storageClass: default
  resourcePolicy: keep
  name: false
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

env:
  SERVER_NAME: "SEAFILE"
  SERVER_IP: ""
  SEAFILE_SERVER_PROTOCOL: "https"
  TIME_ZONE: "Europe/Berlin"
  JWT_PRIVATE_KEY: ""
  SEAFILE_ADMIN_MAIL: ""
  SEAFILE_ADMIN_PASS: ""
  ENABLE_CRON_GC: "1"
  ENABLE_CRON_CLEAN_DB: "1"
  SEAFILE_MYSQL_DB_HOST: "moco-mysql-seafile-primary.seafile"
  SEAFILE_MYSQL_DB_PORT: "3306"
  MYSQL_ROOT_USER: "root"
  INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ""
  SEAFILE_MYSQL_DB_USER: "seafile"
  SEAFILE_MYSQL_DB_PASSWORD: ""
  SEAFILE_MYSQL_DB_CCNET_DB_NAME: "seafile_ccnet"
  SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: "seafile_seafile"
  SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: "seafile_seahub"
  CACHE_PROVIDER: "redis"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  ENABLE_GO_FILESERVER: "true"
  ENABLE_SEAFDAV: "true"

resources:
  requests:
    cpu: "150m"
    memory: "1500Mi"
  limits:
    memory: "2500Mi"
    cpu: "1000m"

ingress:
  enable: true
  groups:
  - secret: example-deploy-tls-tlda
    domains:
    - example-domain.tlda
    - www.example-domain.tlda

notification:
  enabled: true
  image: seafileltd/notification-server:13.0.21
  imagePullPolicy: IfNotPresent
  logToStdout: "true"
  logLevel: info
  resources:
    requests:
      cpu: "25m"
      memory: "64Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

seadoc:
  enabled: false
  image: seafileltd/sdoc-server:2.0.9
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

redis:
  image: redis:8.10.2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "25m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"

nginx:
  image: nginx:mainline
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      cpu: "250m"
      memory: "128Mi"
