server {
	listen			80;
	server_name		_;

	access_log		off;
	error_log		stderr;

	location / {
		proxy_pass          http://${SEAHUB_SERVER_HOST}:8000;
		proxy_redirect      off;
		proxy_set_header    Host $http_host;
		proxy_set_header    X-Real-IP $remote_addr;
		proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Host $server_name;
	}

	location /seafhttp {
		rewrite ^/seafhttp(.*)$ $1 break;
		proxy_pass http://${SEAFILE_SERVER_HOST}:8082;
		client_max_body_size 0;
	}

	location /seafdav {
		rewrite ^/seafdav(.*)$ $1 break;
		proxy_pass http://${WEBDAV_SERVER_HOST}:8080;
		client_max_body_size 0;
	}

	location /notification/ping {
		proxy_pass http://${NOTIFICATION_SERVER_HOST}:8083/ping;
	}

	location /notification {
		proxy_pass http://${NOTIFICATION_SERVER_HOST}:8083/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}

	location /sdoc-server/ {
		rewrite ^/sdoc-server/(.*)$ /$1 break;
		proxy_pass http://${SEADOC_SERVER_HOST}:80;
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		client_max_body_size 100m;
	}

	location /socket.io/ {
		proxy_pass http://${SEADOC_SERVER_HOST}:80;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
